name: keycloak-cluster

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.2
    restart: unless-stopped
    command: 'start-dev'
    ports:
      - "9080:8080"
    volumes:
      - keycloak_themes:/opt/keycloak/themes
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_FEATURES: scripts
      KC_HEALTH_ENABLED: true
    networks:
      - keycloak-network
    depends_on:
      - postgres

  postgres:
    extends:
      file: postgresql.yml
      service: postgresql
    restart: unless-stopped
    networks:
      - keycloak-network
    volumes:
      - postgres:/var/lib/postgresql/data

networks:
  keycloak-network:
    driver: bridge

volumes:
  keycloak_themes:
    driver: local
  postgres:
    driver: local
