name: keycloak

services:
  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_IMAGE_VERSION:-26.2}
    container_name: keycloak
    command:
      - start
      - --proxy-headers=xforwarded
    restart: unless-stopped
    environment:
      # Base y configuración de base de datos
      KC_DB: postgres
      KC_DB_URL: ${DATABASE_URL}
      KC_DB_USERNAME: ${DATABASE_USERNAME}
      KC_DB_PASSWORD: ${DATABASE_PASSWORD}
      
      # Configuración para proxy/balanceador
      KC_PROXY: edge
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME}
      
      KC_HOSTNAME_STRICT: true
      KC_HOSTNAME_STRICT_HTTPS: true
      KC_HTTP_ENABLED: true
      KC_HTTPS_ENABLED: true
      
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true

      # Configuración inicial
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      
      # Configuración de caché para cluster
      KC_CACHE: ispn
      KC_CACHE_STACK: jdbc-ping
      JGROUPS_DISCOVERY_PROTOCOL: TCPPING
      JGROUPS_DISCOVERY_PROPERTIES: initial_hosts=node1[7800],node2[7800]
      
      # Optimizaciones
      JAVA_OPTS: "-Xms512m -Xmx1024m"
    volumes:
      - keycloak_themes:/opt/keycloak/themes
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`openid.sintesis.com.bo`)"
      - "traefik.http.routers.keycloak.entrypoints=web"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
      - "traefik.http.services.keycloak.loadbalancer.healthcheck.port=9000"
      - "traefik.http.services.keycloak.loadbalancer.healthcheck.path=/health/ready"
      - "traefik.http.services.keycloak.loadbalancer.healthcheck.interval=10s"
      - "traefik.http.middlewares.keycloak-https.headers.customrequestheaders.X-Forwarded-Port=443"
      - "traefik.http.middlewares.keycloak-https.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.keycloak.middlewares=keycloak-https"
  